/*****************************************************************************
 * License : All rights reserved for TES Electronic Solutions GmbH
 *           See included /docs/license.txt for details
 * Project : D/AVE NX
 * Purpose : Make build-time svnversion information available
 *           NOTE: THIS FILE IS AUTOGENERATED BY SVNVER SCRIPT
 ****************************************************************************/

#ifndef SVNVER_egl_h
  #ifdef __cplusplus
  extern "C" {
  #endif

  extern char g_egl_svnversion_string[];
  extern char g_egl_svndate_string[];
  extern char g_egl_svnver_fileid[];

  const char *get_egl_svnver_fileid(void);

  #ifdef __cplusplus
  }
  #endif

#endif

